### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by ivastly** [Loopple/loopple#1]
Hello, 

great project, but where is the code? 😃 Looks like you forgot to commit.

Thank you

**Comment by rarestoma** [comment]
Hi @ivastly,

Thank you for using Loopple and for your kind words. Loopple source code is not available, just the generated code is MIT Licensed.

Thank you,
Rares

**Comment by ChrisvanChip** [comment]
@ivastly My best guess is that this repository is used as temporary support system, so to resolve issues of the beta version. Loopple is not an open-source project.

**Comment by rarestoma** [comment]
Hi @ChrisvanChip ,

Thank you for using Loopple. Yes, you're right, this repo is for updated information, issues report, and feedback. If you have any feedback or things that you would like me to implement in future updates, please let me know.

Thank you,
Rares
