### ISSUE TITLE
How to cancel subscription? 

### ISSUE THREAD

**Issue by cjwrights** [Loopple/loopple#11]
Can't find a way to cancel subscription. This isn't what I need. 

Thanks,
Corbin

**Comment by rarestoma** [comment]
Hi @cjwrights,

Thank you for working with Loopple.

We just canceled and refunded your subscription.

Can you please tell us how can we make this product better? What would you like to have?

Thank you,
Rares

**Comment by sher-salafi** [comment]
there is no way to cancel subscription,,, how to cancel....?

**Comment by rarestoma** [comment]
Hi @sher-salafi,

Can you please tell me the email address that you used so I can cancel the subscribtion?

Also, can you please tell me how can we improve Loopple for you?

Thank you,
Rares

**Comment by sher-salafi** [comment]
> Hi @sher-salafi,
> 
> Can you please tell me the email address that you used so I can cancel the subscribtion?
> 
> Also, can you please tell me how can we improve Loopple for you?
> 
> Thank you, Rares

i have replied you on gmail.

**Comment by rarestoma** [comment]
Hi @sher-salafi,

I verified my email addresses but I didn't find any email from you. Can you please send an email to loopplecontact@gmail.com?

Thank you,
Rares
