### ISSUE TITLE
Change my email address in Profile?

### ISSUE THREAD

**Issue by maneeshsethi** [Loopple/loopple#16]
Hi, I can edit the email address on my profile page, but can't save the email.

How do I update my email address?

**Comment by rarestoma** [comment]
Hi @maneeshsethi,

Thank you for working with Loopple.

I just added this option to the 'to-do' list for the next update.

Until then, can you please tell us what email address do you want to replace so we can change it today?

Regards,
Rares

**Comment by wwwanderpe** [comment]
This x2, I need to change my urgent mail and it can't be done, I ask for help


> Hi, I can edit the email address on my profile page, but can't save the email.
> 
> How do I update my email address?

**Comment by rarestoma** [comment]
Hi @wwwanderpe,

Thank you for working with Loopple.

I will fix It in the following days, until then can you please tell me what email you need to change so I can fix it faster?

Regards,
Rares

**Comment by wwwanderpe** [comment]
Thanks, email: wwwanderpe@gmail.com
new email: anderpe495@gmail.com

**Comment by rarestoma** [comment]
Hi @wwwanderpe,

Just changed it now. Please let me know if it works.

Regards,
Rares

**Comment by rarestoma** [comment]
Hi @maneeshsethi, @wwwanderpe,

I just fixed this issue, you can now update your account details.

Regards,
Rares

**Comment by wwwanderpe** [comment]
Thank you!, but my purchase no longer appears!
