### ISSUE TITLE
Issue with sidebar 

### ISSUE THREAD

**Issue by CodeeKid** [Loopple/loopple#17]
Anyone else have a issue with the sidebar in AdminKit not colapsing? Complaining about a missing css file. Buts it is not invluded in the download folder? Please help. Because it was working for like 2 days and then stopped. I even redownload the folder. But still not working.

**Comment by CodeeKid** [comment]
Hi,

Thanks for the reply. Please find attached the video. You can also visit
the site and check yourself.

qsnap.co.za

Regards

**Comment by CodeeKid** [comment]
Hi,

Please see attach the video.

Regards

**Comment by rarestoma** [comment]
Hi @CodeeKid,

Unfortunately, I can't see any video :(

Can you please join our discord channel (https://discord.gg/mU7wgc3tRN) and talk there? I think we can solve the issue faster this way.

Regards,
Rares
