### ISSUE TITLE
Cannot cancel my subscription...... 

### ISSUE THREAD

**Issue by jakepy** [Loopple/loopple#19]
sub_1Jpi4YFBj0zH1wUmIX1GmTJ5

**Comment by rarestoma** [comment]
Hi @jakepy,

Thank you for working with Loopple.

We just canceled your subscription.

Can you please tell us how can we make this product better?

Regards,
Rares

**Comment by Squareflo** [comment]
Can you please cancel my subscription? Or show me how I can do it myself. Thanks

**Comment by rarestoma** [comment]
Hi @Squareflo,

We just canceled your subscription. Can you please let us know how can we make this product better for you?

Regards,
Rares

**Comment by Squareflo** [comment]
ThanksSent from my iPhoneOn Apr 10, 2023, at 9:51 AM, Toma Rares ***@***.***> wrote:﻿
Hi @Squareflo,
We just canceled your subscription. Can you please let us know how can we make this product better for you?
Regards,
Rares

**Comment by ShaneDolphin** [comment]
Please cancel my subscription as well. Just as a general product note, not offering any cancellation or even a form on your site for cancellation is pretty bad.

**Comment by ShaneDolphin** [comment]
My subscription is sub_1MMz3MFBj0zH1wUm30oyyesS


Please cancel.

**Comment by rarestoma** [comment]
Hi @ShaneDolphin,

We just canceled your subscription.

I will also make an update tonight so you can cancel the subscription directly from the dashboard.

Can you please let us know how can we make this product better?

Regards,
Rares
