### ISSUE TITLE
The samples are inaccessible

### ISSUE THREAD

**Issue by RoneoOrg** [Loopple/loopple#2]
Hi,

the samples on your homepage are inaccessible ("500 Server Error")

**Comment by rarestoma** [comment]
Hi @RoneoOrg,

Thank you for using Loopple and for notifying me about this error. I just updated now the samples pages, it works now.

Best regards,
Rares

**Comment by RoneoOrg** [comment]
Indeed, everything works fine now, Thanks
closing
