### ISSUE TITLE
Problem With Purchases 

### ISSUE THREAD

**Issue by KenziEtudiant** [Loopple/loopple#20]
Hi, i buyed the lifetime deal on https://www.loopple.com/sites

But i see that my account is linked with the https://www.loopple.com/profile/purchases

And i don't see anything in purchases 

I can't create more than 1 website on https://www.loopple.com/sites even if i buyed

**Comment by KenziEtudiant** [comment]
Help me thank you

**Comment by rarestoma** [comment]
Hi @KenziEtudiant!

Can you please show us a photo with the sites page where you can't create more website so we can check what happens?

Regards,
Rares
