### ISSUE TITLE
How to edit SoftUI menu icons?

### ISSUE THREAD

**Issue by JonasTheGamer** [Loopple/loopple#3]
Title says it all.. I tried doubleclicking, ...

Also, how do I change table data?

**Comment by rarestoma** [comment]
Hi @JonasTheGamer,

Thank you for using Loopple.

Soft UI Sidenav Icons are SVG's and they can't be edited for now. I will add it to the 'to do' list for the next updates so you can easily change SVG icons from the editor. A full list of the SVG icons available in the Soft UI Dashboard can be found here: https://www.creative-tim.com/learning-lab/bootstrap/icons/soft-ui-dashboard#creative-tim-icons.

You can change table data, like texts or images by clicking/double-clicking on the desired element.

If you have any desired components/features that you would like me to add in the next update please let me know.

Best regards,
Rares

**Comment by JonasTheGamer** [comment]
Thanks for the quick reply! If I want to change the dashboard icon in the
navbar to the ambulance icon (it's in the link you sent) , how would l do
that? Custom svg's is not needed :)

Mvg,
Jonas

Op wo 16 jun. 2021 23:46 schreef rarestoma ***@***.***>:

**Comment by rarestoma** [comment]
Hi Jonas,

Currently, you can change the icon to an SVG one by downloading it and replacing it directly in the code. But I think that it would be a good thing to do that directly in the Loopple interface, what do you think?

Thank you,
Rares

**Comment by JonasTheGamer** [comment]
Oh I see what you're saying now. Great, thanks!

Mvg,
Jonas

Op do 17 jun. 2021 17:32 schreef rarestoma ***@***.***>:
