### ISSUE TITLE
Question - Why only 3 pages?

### ISSUE THREAD

**Issue by riquedev** [Loopple/loopple#4]
First, congratulations on the project, it's amazing.

Why even after having paid we can't make more than 3 pages?
If there is any internal limitation, is a paid self-hosted model possible?

Another less important question, will there be more components available in the near future?

**Comment by rarestoma** [comment]
Hi @riquedev,

Thank you for working with Loopple and for your kind words, it helps us a lot!

I will add it as a priority for PRO users, the possibility to add more pages and we will update it in maximum 2 days.

Also, we will add more components. If you have any component that you personally need, please let me know and we will add it to the priority list.

Best regards,
Rares

**Comment by rarestoma** [comment]
Hi @riquedev,

Just updated, now you can add 10 pages to your project.

Thank you,
Rares

**Comment by riquedev** [comment]
> Hi @riquedev,
> 
> Just updated, now you can add 10 pages to your project.
> 
> Thank you,
> Rares

Thanks !!
