### ISSUE TITLE
XSS vulnerability (outdated jQuery) & Don't use jQuery behind CloudFlare (demos.creative-tim.com)

### ISSUE THREAD

**Issue by ChrisvanChip** [Loopple/loopple#6]
Hey @rarestoma,

I tried using your builder today to see whether or not it was improved, and I could not get past the pricing table. The buttons didn't interact.
![image](https://user-images.githubusercontent.com/31969757/132255696-26c17cb3-5708-4c8b-a33e-5c39ccb70a00.png)

After a little investigation, you seem to use the `jquery.min.js` from a third-party demonstration URL that uses CloudFlare on their assets.
https://demos.creative-tim.com/argon-dashboard/assets/vendor/jquery/dist/jquery.min.js

Please consider moving away from `jQuery v3.4.1` (the one hosted by Creative Tim demo), it has bugs, is less compatible (since it's older) and has XSS vulnerabilities.
https://snyk.io/vuln/npm:jquery@3.4.1

A drop-in replacement would be the usage of a [jQuery CDN](https://code.jquery.com), such as:
https://code.jquery.com/jquery-3.6.0.min.js

Looking forward to your fixes and further evolution of the builder! :)

**Comment by rarestoma** [comment]
Hi @ChrisvanChip,

Thank you for pointing us this issue, we just replaced the jQuery link right now. 

Can you please let me know if it works now?

Thank you,
Rares

**Comment by ChrisvanChip** [comment]
Can confirm that the jQuery issue has been solved at the pricing page, however I noticed the builder is relying on the CloudFlare-protected third-party assets too.

![image](https://user-images.githubusercontent.com/31969757/132387141-11c94e31-0298-490a-b885-138006a30f31.png)

My strong recommendation is to host this on your own server, to prevent outages, avoid vulnerabilities and have full control over updates.

**Comment by rarestoma** [comment]
Hi @ChrisvanChip,

Thank you for pointing us to these issues, it helps us a lot. I will notice it to fix on the following updates. 

Can you please give us an email at loopplecontact@gmail.com so we can reward you for your help?

Best regards,
Rares

**Comment by ChrisvanChip** [comment]
> Hi @ChrisvanChip,
> 
> Thank you for pointing us to these issues, it helps us a lot. I will notice it to fix on the following updates.
> 
> Can you please give us an email at [loopplecontact@gmail.com](mailto:loopplecontact@gmail.com) so we can reward you for your help?
> 
> Best regards,
> Rares

Thank you for your response! I have sent an email from @bloxtech.tech and the character count is `764`, so you can verify the email is coming from me.

Let me know if you need any more information from my side :)

**Comment by ChrisvanChip** [comment]
I believe this issue has been resolved now, please reopen if necessary 🙃
