### ISSUE TITLE
Copy pages/navbar/meny

### ISSUE THREAD

**Issue by Frixnor** [Loopple/loopple#8]
Love Loopple and fully understand that not all is in place from day one.

Either I do not understand how or it is not possible, but would love to copy pages/navbar/meny so I can save time when adding mutiple pages.

**Comment by rarestoma** [comment]
Hi @Frixnor,

Thank you for your support and for working with Loopple. 

Currently, this option is not available but is a good option that we will add to the 'to do' list for the next update. 

Best regards,
Rares

**Comment by Frixnor** [comment]
💪🏻👍🏻
